# -*- coding: utf-8 -*-
"""ランサムウェア基礎知識確認用プログラム.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1isOg9FwDaGx104cKESWWF681Dv9UbvHb

# 暗号化
"""

! pip install cryptography
from cryptography.fernet import Fernet

"""
このコードもローカル必須

.tex 暗号化版

実行はコマンドプロンプトから
.py 推奨
"""

from cryptography.fernet import Fernet

#キーを作成する
key = Fernet.generate_key()

#キーをローカルに保存する
with open(r"C:\Users\user\test\test_key.key","wb") as key_data:
    key_data.write(key)

#暗号化するファイルの取得
with open(r"C:\Users\user\test\test.txt","r") as file:
    data = file.read()

print("暗号化する前: ",data)

#データをバイトに変換する
byte_data = data.encode()

#Fernetオブジェクトの初期化
f = Fernet(key)

#バイトデータを暗号化する
encrypt_data = f.encrypt(byte_data)

#暗号化した情報をファイルに書き込む
with open(r"C:\Users\user\test\test.txt","wb") as file:
    file.write(encrypt_data)

print("暗号化した後: ", encrypt_data)

"""
復号版
"""
from cryptography.fernet import Fernet

#キーの読み込み
with open(r"C:\Users\user\test\test_key.key","rb") as test_key:
    key = test_key.read()
#暗号化したファイルの読み込み
with open(r"C:\Users\user\test\test.txt","rb") as file:
    encryp_data = file.read()

print("暗号化された情報: ",encryp_data)

#キーを使ってFernetオブジェクトを初期化
f = Fernet(key)
#データの復号化
decrypt_data = f.decrypt(encryp_data)

print("復号化した情報: ",decrypt_data.decode('utf-8'))

"""# 通信"""



"""# ファイル確認"""

"""
ファイルの簡易的な情報を手に入れるとこができる
ローカルにあることが必須
"""
import os
filename = "/Users/flavio/test.txt"


print(os.path.getsize(filename))
# アイテムサイズ
print(os.path.getmtime(filename)) 
# アイテム最終更新日
print(os.path.getctime(filename)) 
# アイテム作成日

print(os.stat(filename)) #アイテムのすべての情報を簡潔に表示